apiVersion: v1
kind: Service
metadata:
  name: tomcat-app
spec:
  selector:
    app: tomcat-app
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
  labels:
    app: tomcat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-app
        image: 415707351810.dkr.ecr.ap-south-1.amazonaws.com/cmas_tomcat:latest
        ports:
        - containerPort: 8080